<a
    {{
    $attributes->merge(['class'
    =>
    'text-black
    bg-gray-800
    hover:bg-gray-900
    focus:outline-none
    focus:ring-4
    focus:ring-gray-300
    font-medium
    rounded-lg
    text-sm
    px-3
    py-2
    me-2
    mb-2
    dark:bg-yellow-300
    dark:hover:bg-yellow-700
    dark:focus:ring-gray-700
    dark:border-gray-700'])
    }}>{{
$slot
}}</a>
