<a
    {{
    $attributes->merge(['class'
    =>
    'bg-gray-800
    hover:bg-gray-900
    focus:ring-4
    focus:ring-gray-300
    rounded-lg
    text-sm
    px-3
    py-1
    p-2
    m-2
    dark:hover:bg-gray-700
    dark:focus:ring-gray-700
    dark:border-gray-700'])
    }}>{{
$slot
}}</a>
